### ISSUE TITLE
Default kui table enhancements

### ISSUE THREAD

**Issue by showeimer** [kubernetes-sigs/kui#1865]
The advantage of KUI is having a UI output that makes it easier to visualize and work with data.  The KUI tables should be enhanced to support the following to make them more useful:

- [ ] Column sorting
- [x] Pagination (include a page size dropdown)
- [ ] Search bar? (less necessary when user can use `grep`)

**Comment by starpit** [comment]
#3630 adds a Table rendering impl that uses Carbon Components. It offers pagination, with the threshold for pagination governed by a setting in `@kui-shell/client/config.d/tables.json`.

this renderer could be augmented to support sorting, etc. we did not include sorting in the first drop, because: 

1) sorting versus pagination will need to be worked out
2) there seems to be a bug in carbon: if you ask for a column to be sortable, you cannot offer any className attributes (or any attributes, for that matter) to be attached to the header cell. we have a "hide with sidecar" feature that requires adding className to the table header; so this issue would need to be worked through, too.
