### ISSUE TITLE
[GVT]run 'help' - some strings are translated but still display as English in UI

### ISSUE THREAD

**Issue by WalterFang** [kubernetes-sigs/kui#2669]
**Describe the bug**
 Some strings are translated but still display as English in KUI. This issue happens to all translated languages.

**Steps to reproduce the behavior**

1. Go to KUI GUI in macOS
2. Run the command 'help'
3. See below screen capture

**Expected behavior**
The strings in red  rectangles shoud display as translated languages.

**Screenshots**
The strings in red rectangles are translated, but still display as English. 
![02 010 010__CHS](https://user-images.githubusercontent.com/8808972/64414817-a1503100-d0c6-11e9-9b5b-7964cd0f07c0.jpg)

**System**

- Kui version: 4.0.0-dev.4281.20190904142907
- Operating system: macOS Mojave v10.14.6

**Comment by starpit** [comment]
thanks for the bug report!

**Comment by myan9** [comment]
We initially thought we have some strings not externalized, but it turns out not to be the truth. The only string not-externalized is `A summary of the top-level command structure`. Try `open --help`, and you should see the translated files. The root problem here is the way we import the usage model into the help command, and we can also see a lot of improvements needed in the help content.
