### ISSUE TITLE
echo $SHELL is wrong

### ISSUE THREAD

**Issue by docwhat** [kubernetes-sigs/kui#5041]
`echo $SHELL` returns `/bin/zsh`  but that is obviously false; it has none of the features of ZSH.

`echo $BASH_VERSION` returns `3.2.57(1)-release` which matches macOs's `/bin/bash` version.

**Comment by starpit** [comment]
thanks for identifying these issues. any thoughts?

Some notes of the Kui architecture:

- Kui proxies commands to an underlying shell. it currently does so via an underlying `bash` (on mac and linux) or powershell (on windows).

- At the same time, it gathers your environment variables and aliases from whatever SHELL you have configured as your default (zsh, in your case). 

- The reason kui fixes the proxied requests to bash (rather than your default SHELL) is something we can fix, but is mostly just a statement in time.

- Why doesn't kui hold open a connection to an underlying (and durable) shell process? this is a possibility, but doing so would require some rethinking of the Kui REPL. Kui's read-eval-print-loop decides whether the command will be serviced by a Kui plugin, or by an underlying shell process. since Kui is in charge of the REPL, it therefore needs to know when a command execution completes (so it can Loop!). we weren't sure if this was possible to manage via a persistent shell process (where the job control is, to the best of our knowledge, a mostly opaque affair managed by the shell).

**Comment by docwhat** [comment]
Is the `bash` version included in KUI or is it hard coded to `/bin/bash`?  It might be better to include the shell in KUI itself on UNIXy platforms.

The problem/danger with using the user's shell configuration in their prompt may be complex and hard to render. e.g. my zsh problem requires [Nerd Fonts](https://www.nerdfonts.com/).

If you can point at the REPL code, maybe I can think of something.  I've done lots of shell stuff, including (for example) executing commands over a standing `ssh` connection.  There are tricks you can use to detect what's going on.

**Comment by oskapt** [comment]
>     * At the same time, it gathers your environment variables and aliases from whatever SHELL you have configured as your default (zsh, in your case).

It doesn't seem to do a good job of this. I use fish, and every command I run in Kui has this before the output:

```
bash: alias: doh-client: not found
bash: alias: docker run --rm -it monachus/doh-tools client: not found
bash: alias: hey: not found
bash: alias: docker run --rm -it rcmorano/docker-hey: not found
bash: alias: k: not found
bash: alias: kubectl: not found
bash: alias: ka: not found
bash: alias: kubectl apply: not found
bash: alias: kak: not found
<snip>
```

My best guess is that this is because, while the fish `aliases` file follows a bash-like format, the output of the `alias` command does not:

```
➤ alias
alias doh-client 'docker run --rm -it monachus/doh-tools client'
alias hey 'docker run --rm -it rcmorano/docker-hey'
alias k kubectl
alias ka 'kubectl apply'
```

Would this be easy to fix with some regex magic before passing it off to Bash, or with error handling to dump aliases that don't follow the correct format? Since everything is bounced to a new Bash shell, there doesn't seem to be any way to avoid this or filter it out, and it makes Kui unusable for me.

UPDATE: I was able to get around it by converting all my aliases to functions by recreating them with `alias -s` and then deleting `aliases.fish`:

```
cat aliases.fish | sed -E 's/^alias //' | grep -vE '^$' | grep -Ev '#' | while read x; set name (echo $x | awk -F= '{ print $1 }'); echo $name; set val (echo $x | awk -F= '{ print $2 }'); if ! test -f ~/.config/fish/functions/$name.fish; alias -s $name=$val; end; end
```
