### ISSUE TITLE
Notebooks do not preserve history of watchable table updates

### ISSUE THREAD

**Issue by myan9** [kubernetes-sigs/kui#5399]
~- [x]  new tab~

- [x] new split

- [x] `pexec` without echo can not be replayed, e.g. clicking the new split button. We should still capture the no-echo exec in the BlockModel, but not render it. We could also render the click exec as a commentary block showing, for example.,`<You clicked on row 1 of Out[1]>`. Then, we can teach others to get the resource shown in Sidecar when others replay the snapshots.

~- [x] React Response are not replayable. ~~We could solve this by either using React serializer or ask controller to return a React Model instead of React Component.~~  Every command response should be a self-contained model.~

- [x] The change of view states is not preserved in snapshot, e.g. switching the table view format from List to Grid, switching to the second tab of Sidecar.

- [ ] Watch capability is not serializable or replayable. Currently the watch capability is done by the `Watchable` instance in a response, which can't be serialized or replayed. To solve this issue, maybe a response could have a watch command that generates a `Watchable` response, and then we can re-invoke that command, and even add the watch capability to a non-watchy response.

**Comment by starpit** [comment]
i have crossed out new tab, because for now the notebook model is single-tab

i have also crossed our React component response serialization. this does not seem like something we can contain for now. server-side react includes some marshalling logic, but not of the AST (which is what we need) but rather of the final rendered form (which is not what we want to store in the notebook); there is a react marshalling npm, but it seems rather buggy.
