### ISSUE TITLE
kui Failing to build on x86_64 

### ISSUE THREAD

**Issue by ghost** [kubernetes-sigs/kui#5892]
I am trying to build kui on my 64 bit x86 machine with ubuntu bionic setup.
I have followed below steps to build the package:
~~~
1.  git clone https://github.com/IBM/kui.git
2.  cd kui
3.  npm ci
4.  npm start
~~~

npm ci completes fine, but npm start stucks after some time. 

Below are the logs when command stucks:
~~~
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/language/json/json.worker.js] 628 bytes {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/language/json/jsonWorker.js] 11.2 KiB {main}
[WEBPACK]         + 46 hidden modules
[WEBPACK] Child vs/language/typescript/tsWorker:
[WEBPACK]            Asset      Size  Chunks  Chunk Names
[WEBPACK]     ts.worker.js  10.5 MiB    main  main
[WEBPACK]     Entrypoint main = ts.worker.js
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/base/common/arrays.js] 6.71 KiB {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/base/common/diff/diff.js] 44.6 KiB {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/base/common/errors.js] 2.65 KiB {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/base/common/lifecycle.js] 5.14 KiB {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/base/common/platform.js] 4.33 KiB {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/base/common/types.js] 4.14 KiB {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/base/common/uri.js] 20.6 KiB {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/base/common/worker/simpleWorker.js] 9.87 KiB {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/editor/common/core/position.js] 3.8 KiB {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/editor/common/services/editorSimpleWorker.js] 19.2 KiB {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/editor/editor.worker.js] 1.02 KiB {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/language/typescript/lib/lib.js] 1.47 MiB {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/language/typescript/lib/typescriptServices.js] 8.35 MiB {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/language/typescript/ts.worker.js] 656 bytes {main}
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/language/typescript/tsWorker.js] 16.9 KiB {main}
[WEBPACK]         + 24 hidden modules
[WEBPACK] ℹ ｢wdm｣: Compiled with warnings.
~~~
After this, I am not getting the prompt.....terminal just hangs here.

I just want to build kui on x86_64 machine and generate the binaries. Also, there is no build folder getting created.
Can you please help me where I am getting wrong, or it would be helpful if you can share some documentation.
Looking for a positive response soon :)

**Comment by wichpatricke** [comment]
Here are my system details:

**Comment by starpit** [comment]
Howdy! Thanks for the bug report. We have been successful with Ubuntu in travis, Ubuntu 18.04, and most recently Ubuntu 20.04. When you say:

> After this, I am not getting the prompt.....terminal just hangs here.

Do you mean that you see a Kui window open, but the window is blank?

**Comment by starpit** [comment]
Also, have you verified whether (or not) the prebuilt images work for you?

**Comment by wichpatricke** [comment]
Thank you @starpit for the response.
>Do you mean that you see a Kui window open, but the window is blank?

No, kui window does not open. I am still on normal terminal. 'npm start' runs and halts at the logs below:
~~~
[WEBPACK]     [./node_modules/monaco-editor/esm/vs/language/typescript/tsWorker.js] 16.9 KiB {main}
[WEBPACK]         + 24 hidden modules
[WEBPACK] ℹ ｢wdm｣: Compiled with warnings.
~~~
If I press Cntl+C, then following logs are seen:
~~~
[WEBPACK]         + 24 hidden modules
[WEBPACK] ℹ ｢wdm｣: Compiled with warnings.
^C[ES6] npm run watch:source exited with code SIGINT
--> Sending SIGTERM to other processes..
[WEBPACK] npm run watch:electron exited with code 0
~~~
Do you think I am missing something here? I just installed npm via apt-get, then cloned 'kui' and ran 'npm ci' and 'npm start'. Do I need to execute something more here?

>Also, have you verified whether (or not) the prebuilt images work for you?

No, I have not used the prebuilt images. Actually I wish to generate my own kui binaries, that's why I am building kui from source. My main motive is to run kui on raspberry after successful testing it on x86_64 system.

**Comment by wichpatricke** [comment]
@starpit 
I have executed the same steps to build kui on raspberry, and getting the same issues. 'npm start' command just halts after logs shared above.
Raspberry uses 64 bit arm processor. So, I also tested kui with 64 bit arm on travis-CI. That has shown below error for chrome not getting started.
~~~
Error: unknown error: Chrome failed to start: exited abnormally
(chrome not reachable)
(The process started from chrome location /home/travis/build/buzo/kui/node_modules/spectron/lib/launcher.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
(Driver info: chromedriver=78.0.3905.1 (adc3a81bb97a90bf5417e850ea9d612cdbfcdef4-refs/heads/master@{#703739}),platform=Linux 5.3.0-42-generic aarch64)
~~~
Earlier I thought it's because chromium does not support arm, but then found that code downloads electron and chromedriver both during npm ci, and both binaries are available for 64 bit arm, as can be seen here <https://github.com/electron/electron/releases/tag/v7.3.2>. So probably the issue is something else.

Hence, now I have two challenges, one is to build kui on 64 bit x86 machine, and second is to resolve this chrome failure error on arm jobs on Travis.
Can you please provide some pointers here ?...

**Comment by starpit** [comment]
hello! re: arm64, we have not yet tried arm ourselves. we'll have to look into this to see what is going on.

for x64, could you run running two separate commands:
```sh
npm run watch
```

then, when you see this
> [WEBPACK] ℹ ｢wdm｣: Compiled with warnings.

run 
```sh
npm run open
```

either in a separate tab, or after backgrounding the watcher. If nothing happens when you do the `open`, you can also try adding 

```sh
DEBUG=* npm run open
```

This is what a normal debug output would emit:

❯ DEBUG=* npm run open

```sh
> kui-shell@9.0.0 open /Users/nickm/git/whisk/nickm/kui
> electron . shell

  main/main loading +0ms
  main/main it looks like this is the main entry point, rather than a require +2ms
  main/main shortcut to graphics +0ms
  main/spawn-electron loading +0ms
  main/spawn-electron getCommand [
  '/Users/nickm/git/whisk/nickm/kui/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron',
  '.',
  'shell'
] +0ms
  main/spawn-electron isShell [ '.', 'shell' ] shell +1ms
  main/spawn-electron using args [ 'shell' ] {} +0ms
  main/spawn-electron initElectron [ 'shell' ] false {} +1ms
  main/spawn-electron loading electron +0ms
  main/main isRunningHeadless false +6ms
  main/main all done here, the rest is async +0ms
  main/spawn-electron loading electron done +0ms
  main/spawn-electron exiting, since we are not the first instance +350ms
```

**Comment by wichpatricke** [comment]
> hello! re: arm64, we have not yet tried arm ourselves. we'll have to look into this to see what is going on.

Oh!!! ok...I will test it myself and let you know the results.

> npm run watch

Yes, I have tried these commands. 
**_npm run watch_** worked fine and ended at 
~~~
[WEBPACK] ℹ ｢wdm｣: Compiled with warnings.
~~~
After that, I pressed cntl+C.
Now, when I run **_npm run open_**, I get following issue
~~~
[14823:1009/133947.533017:FATAL:atom_main_delegate.cc(211)] Running as root without --no-sandbox is not supported. 
~~~
I have checked that --no-sandbox option is already present in common.ts file for chrome. 
I am confused here why I am getting this --no-sandbox issue.

**Comment by starpit** [comment]
Interesting. Thanks for the additional info. Are you running as root? I guess we have never tried that. If you are, we can give it a shot, and see if we can repro this.

**Comment by wichpatricke** [comment]
@starpit 
When I am running **_(npm run watch)_** and **_(npm run open)_** without root, Both are passing well. Here is the output to **_(npm run open)_**
~~~
> kui-shell@9.0.0 open /home/patricke/kui
> electron . shell
~~~
After this, I ran **_(npm run testv2 core)_**. This seems problematic and gave issues to start chrome. 
~~~
error refreshing in before for fresh start { Error: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/patricke/kui/node_modules/spectron/lib/launcher.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
~~~
Are there some dependencies that I need to install for the chrome to work properly?

**Comment by starpit** [comment]
This could be it. Could you try 

```sh
sudo apt install chromium-browser
```

Which might be a way to pull in the needed X dependencies? They had seemed to be installed by default on Ubuntu 20, which i just provisioned, fwiw.

**Comment by wichpatricke** [comment]
Already did that...but that installs newest versions of chromium-browser....85.XX series.
And chromedriver used in kui is 78.XX, as seen from the logs 
~~~
(The process started from chrome location /home/patricke/kui/node_modules/spectron/lib/launcher.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=78.0.3905.1 (65dc90a9851d018b9423492f01b15f06cc34beba-refs/heads/master@{#703739}),platform=Linux 5.0.0-23-generic x86_64)
~~~
But I thought chromium-browser gets installed during npm ci, and I don't require to install it otherwise....Guess I proved wrong here.
And even if I install latest chromedriver...i.e. 86.XX series.....again errored logs show driver version 78.XX.
Is there a way I can update the driver version in kui??

**Comment by starpit** [comment]
i see. hmm. would it be possible for you to try the browser-based angle? so that we can factor electron out of the equation (for now)?

```sh
npm run watch:webpack
```

and, when the watcher is up, try visiting `localhost:9080`? we do this in travis, and i just verified it in an ubuntu 20 VM. a few weeks ago, i did this successfully in an ubuntu 18 VM.

if you are able to build and access kui via a browser, at least it'll help to isolate the problem. this will also help you make progress, as you can then have an edit-debug loop. if you are modifying typescript source, make sure also to run:

```sh
npm run watch:source
```

the `npm run watch` target combines the typescript watcher and webpack watcher; however, at the moment, when  you use the `npm run watch:webpack` target, it only spawns the webpack watcher.

**Comment by wichpatricke** [comment]
I think I am not getting what exactly you want to guide here 
>and, when the watcher is up, try visiting localhost:9080?

If I am not wrong, do you mean to run 
~~~
npm ci
npm run watch:webpack
npm run open
npm run testv2 core
~~~
If yes, then I have tried executing **_npm run watch:webpack_** and then **_npm run open_**, and it ended well. But again after **_npm run testv2 core_**, I got chrome error as before. 
However, **_npm run watch_** was also ending well earlier, without error, and the chrome problem starts with **_npm run testv2 core_** itself.
TBH, I am not clear with this line...
>and, when the watcher is up, try visiting localhost:9080? 

can you please bother to explain a little more, if possible :)

**Comment by starpit** [comment]
```sh
npm ci
npm run watch:webpack
```

when that is done, you can try opening up any old web browser, and visiting `http://localhost:9080`. if that works, then we have isolated the problem to be an issue with electron on your OS/platform.

to run tests against this, you will need a small variant of the test launch. you can see the `test:webpack` target in package.json. all it does it set two environment variables; these two env vars tell the test rig to initialize a connection independent of electron: 

```sh
KUI_USE_PROXY=true MOCHA_RUN_TARGET=webpack npm run testv2
```
