### ISSUE TITLE
Unable to set variable to command output

### ISSUE THREAD

**Issue by jt-nti** [kubernetes-sigs/kui#6319]
**Describe the bug**

I would like to be able to create a notebook without revealing any API keys, so I wanted to set a shell variable to avoid command output with API keys being visible. Unfortunately it doesn't appear to be possible to use `$(command)` command substitution, or backticks. I even tried using `read`

**Steps to reproduce the behavior**

1. Try to set a variable using one of the following...

```
export KEY=$(command)
```

or...

```
export KEY=`command`
```

or...

```
command | read KEY; export KEY
```

**Expected behavior**

I should be able to use the `$KEY` environment variable in subsequent commands

**Screenshots**

![image](https://user-images.githubusercontent.com/3535067/101166901-ef891280-3630-11eb-91d4-98c4bb0d6288.png)

**System**

- Kui version: recent (I couldn't find the version in the UI anywhere, sorry)
- Operating system: OSX

**Comment by starpit** [comment]
Hello, and thanks for the bug report. Yup, this makes sense. Let us ponder for a bit.

**Comment by jt-nti** [comment]
Thanks. I did wonder afterwards if there might be other options to extend Kui to handle these kind of secrets as well/instead. Not entirely sure how though!

**Comment by jt-nti** [comment]
Hi @starpit did you get a chance to ponder this issue and come up with anything or should I let it close?

**Comment by oskapt** [comment]
Please reopen this. It's still an issue.

I am keen on using Kui with trainings that I do for SUSE/Rancher. It would make it easy for students to follow along and have the notebooks use variables that automatically customize themselves for each student's environment:

```
export IP=$(kubectl get service/traefik -n kube-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
export PORT=$(kubectl get service/demo -o jsonpath='{.spec.ports[0].nodePort}')
curl -I $IP:$PORT
```

Every time I try this, I run into this limitation around command substitution. It would be excellent if Kui supported it so that notebooks could be adaptable, allowing students to focus on learning instead of focusing on figuring out what IP was assigned to the ingress controller in their specific distribution of Kubernetes.

**Comment by jt-nti** [comment]
It looks like the problem is due to the export command implementation. For example, it also fails to handle this...

```
export PATH=$HOME/bin:$PATH
```

...with unfortunate consequences :)

Not sure what the best fix is but maybe spawning a shell to handle the export command and grabbing the result would work?

https://github.com/kubernetes-sigs/kui/blob/master/plugins/plugin-bash-like/src/lib/cmds/export.ts#L29

**Comment by starpit** [comment]
This should be doable. We'll take a shot at it for the upcoming 10.4.0 release.
