### ISSUE TITLE
Option to close the output window

### ISSUE THREAD

**Issue by RealHarshThakur** [kubernetes-sigs/kui#7060]
When I run a command to view a resource, I would like to close the output window on the right hand side as it takes a lot of space. I think this was possible in previous versions.

**Comment by starpit** [comment]
Hello, and thanks for the feedback!

The split to the side is now a normal terminal split. You may close it as you would any terminal, e.g. via ctrl+d or by typing "exit". 

We have been brainstorming on a way to make this kind of "one-off drilldown" more convenient. Perhaps having a close button somewhere in each split? Or should Escape close the currently-focused split? Thoughts?

**Comment by RealHarshThakur** [comment]
@starpit Yes, that would be nice. I really like the current setup as it has screenshot functionality and scrolling to previous outputs. Although It would be nice to have the maximize and close button like the older version does . 
![image](https://user-images.githubusercontent.com/38140305/108722123-b15a0b80-751a-11eb-874d-8e3a3246db2a.png)

**Comment by starpit** [comment]
Great idea! We'll try to cook something up.

**Comment by starpit** [comment]
To start with, we have added some lightweight placeholder text to instruct users that ctrl+d will close the split (ctrl+d was already supported, but now Kui advertises this a bit more). https://github.com/IBM/kui/pull/7068

The keyboard strategy for this is: 
1) `k get pods` (e.g.)
2) click on myPod
3) <inspect the pod>
4) ctrl+d to close; as long as you have not otherwise clicked around, the prompt in the new split will have focus, and so ctrl+d without any mouse motion will immediately close that new split

This isn't a 100% solution, but hopefully it goes some way towards addressing this UX issue. Clearly the entire issue remains unresolved, so this issue will remain open.

The ctrl+d placeholder text enhancement was released in [10.2.0](https://github.com/IBM/kui/releases/tag/v10.2.0).

**Comment by starpit** [comment]
We have merged in some UI enhancements that will be released soon, with 10.4.0. Each split pane will now have its own close button.

<img width="1024" alt="Screen Shot 2021-06-08 at 12 55 34 PM" src="https://user-images.githubusercontent.com/4741620/121226675-d3249780-c858-11eb-89e3-871e4d1bfb27.png">

**Comment by RealHarshThakur** [comment]
Awesome @starpit ! Thanks, really appreciate this.
