### ISSUE TITLE
KUI does not return the same output for oc/kubectl

### ISSUE THREAD

**Issue by haf-tech** [kubernetes-sigs/kui#7399]
**Describe the bug**
kubectl command does not return the correct response in KUI,  compared to a normal terminal session.

**Steps to reproduce the behavior**

1. execute the same command in KUI and in a normal termin
2. expect the same output

**Expected behavior**
Same output, also for non default k8s resource types

**Screenshots**
![Screenshot 2021-05-13 at 18 06 03](https://user-images.githubusercontent.com/29369954/118153338-12a4c300-b416-11eb-8c6f-0980d38be02f.png)

**System**

- Kui version: 10.2.1
- Operating system: MacOS

**Comment by starpit** [comment]
Howdy, thanks for the bug report! We will look into this tomorrow or the next day, we hope!

**Comment by starpit** [comment]
Hmm, at least without the `-n` it seems to work. 🤔

**Comment by starpit** [comment]
The situation here is that of partially qualified resource kinds.

Unqualified: service
Fully Qualified: service.<version>.<group>   (where apiVersion=<group>/<version>)
Partially Qualified: service.group

It turns out that `kubectl get` and `oc get` support all three forms. And they have heuristics on how to disambiguate the first and third cases.

Kui has a bug in the third case that we'll fix. But it's worth noting that, even with kubectl or oc on their own (i.e. independently of Kui), `kubectl get` calls against partially qualified resource kinds can be considerably slower than either unqualified/unambiguous or fully qualified lookups. They can often be 4-5 TIMES slower.

So you may want to determine the `version` part of your kind, it could speed things up for you. On the Kui side, we can at least fix the bug so that the (probably much slower) partially qualified lookups work.
