### ISSUE TITLE
Homebrew install: "Kui.app" cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by jsolbrig** [kubernetes-sigs/kui#8002]
**Describe the topic**
I installed Kui using `brew install kui`, but when I try to run the executable I get `"Kui.app" cannot be opened because the developer cannot be verified`. While I know how to get around this, I think this will be a deterrent to people (including me) using Kui. Are there plans to get Kui verified with Apple?

**Comment by starpit** [comment]
Howdy, yes! We are already set up to allow for signed+notarized builds. Unfortunately, due to Apple's recent switch to enforcement of its "hardened runtime" (in macOS 11), combined with a [bug in libuv](https://github.com/electron/electron/issues/26143)... the result is that signed+notarized builds are excessively slow -- adding about 300ms to every subprocess execution.

The libuv people have been trying to fix this for quite a while. In their latest attempt, they have run into macOS kernel bugs (sigh)... But I think they are close.

So... on the Kui side, we could decide to use signed+notarized builds, with a slowness/lag warning... It depends which is prioritized, UX latency/responsiveness versus unsigned builds. Thoughts?

**Comment by starpit** [comment]
For a bit more detail: when using the hardened runtime, the POSIX `fork` call is very slow, because it has to copy lots of state. The solution is to use the newer `posix_spawn` API. But this is apparently new enough to be still buggy. Why Apple thought they could mandate the use of a buggy API is beyond me.

**Comment by jsolbrig** [comment]
I think that to give a good answer to your question I'd need to be able to test how intrusive the UX latency/responsiveness issues are. I'd be happy to test things and give you my opinion if that's possible. 

I'm personally giving Kui a test drive right now, but I don't think I'm going to recommend it to coworkers until it's signed.

That's really frustrating that Apple made changes without a viable solution in place.

**Comment by starpit** [comment]
Agreed. We can make a build for the next patch release and upload it to the releases page. I'll ping this thread when that happens. We could probably release something by EOD, or some time tomorrow.

**Comment by jsolbrig** [comment]
Sounds great! I'll keep an eye out for it and will give it a try tomorrow. I don't think I'll have time to test by EOD today.

**Comment by starpit** [comment]
The [10.5.5 release](https://github.com/kubernetes-sigs/kui/releases/tag/v10.5.5) has signed builds for darwin x86 and arm64. I just tried it on x86. It is definitely laggy, though still usable.

**Comment by starpit** [comment]
At long last, Kui 11.0.0 (just released to homebrew: `brew upgrade kui`) now ships with signed+notarized builds for macOS.
