### ISSUE TITLE
spinners in notebooks when executing the command and the output is still not ready

### ISSUE THREAD

**Issue by atinsood** [kubernetes-sigs/kui#8025]
currently for notebooks on clicking the play button, the play button disappears while the command is getting executed and the output is not ready. 

an enhancement to this behavior can be a spinner that is displayed while the command is getting executed but the output is still not ready.

**Comment by starpit** [comment]
Currently, I think notebooks never show spinners. We should change this so that we only avoid showing spinners for blocks that haven't be re-executed. The original intent was to avoid showing e.g. the duration of the original command when displaying the notebook author's pre-recorded output. But when the user of the notebook re-executes that command, I agree we should show spinners and duration.

**Comment by starpit** [comment]
Reopening to allow for full solution (actually add spinners, as requested!)

**Comment by starpit** [comment]
There are a number of bugs in this area. For example, 

- when editing and re-executing with a different command line, the command line transiently reverts to the initial command line, then pongs back to the updated command line when the re-execution completes.
- no spinners at all for blocks being re-executed
- also no duration count-up for blocks being re-executed
- old Output continues to be shown while block is being re-executed
