### ISSUE TITLE
Can I associate a context with a tab?

### ISSUE THREAD

**Issue by pwright** [kubernetes-sigs/kui#9090]
Trying to figure out the best way to create a notebook that switches kube context as they proceed thru steps.

With skupper.io we have automatically rendered README.md files to illustrate various examples, eg https://github.com/skupperproject/skupper-example-hello-world

I think it might be possible to redirect the markdown to kui to give a great experience for new skupper users, but I'm new to kui and don't know the best way to approach it.

With skupper, you switch between clusters/namespaces for each procedure 'step', and I thought I could use 'tabs' for this experience, for example:

![image](https://user-images.githubusercontent.com/5154224/200308601-fe36e992-0262-4c74-818a-0582482799aa.png)

but I'm not sure if it's possible to tie each tab to a kube context, or if there is another approach I should try?

thanks in advance for a super tool, any 'getting started' links appreciated.

currently using steps like:

```

=== "west"

    ~~~ shell
    kubectl create deployment frontend --image quay.io/skupper/hello-world-frontend
    ~~~

=== "east"

    ~~~ shell
    kubectl create deployment backend --image quay.io/skupper/hello-world-backend --replicas 3
    ~~~

```

**Comment by starpit** [comment]
hello there. thanks for sharing some great thoughts!

each top-level tab in kui should lock itself to a kubernetes context, but currently this only happens after a command execution, in that tab, to change context.

markdown tabs currently do not have this capability.

one thing we could do is add a bit of metadata support to kui's markdown code block implementation. right now, you can express things like

    ```shell
    ---
    execute: now
    ---
    ```

i.e. kui does support adding a "topmatter" element to each code block (in this case, the `execute: now` tells kui that you want it to execute the code block on the initial render, rather than when the user clicks to execute.

we could add `context: xxx` support, perhaps? or maybe more generally, a `suffix: --context west`, where kui will automatically add the given suffix to the command line execution?

🤔

**Comment by pwright** [comment]
Thanks @starpit 
So, if i was to approach this (without major customization), I would set up two top level tabs:

East
0. Set kube context
1. Perform step  
2. Switch to West tab to perform step X
3. Perform step

West
0. Set kube context
1. Perform step
2. Switch back to East tab to perform step Y
3. Perform step

I'm not sure how auto-executing steps would help me, so, for now I think my best option is to generate markdown with the context embedded, eg `skupper init --namespace west` 

thanks @starpit Any pointers for new kui users who want to create markdown notebooks, I'm currently using https://github.com/kui-shell/KuiClientTemplate but I dunno if that's the best option... Ideally I want the flow for skupper users to be:

- Install kui
- Run the skupper notebook

but is that what folks do? (I'm not finding any doc for that flow)
